server:
  port: 8123
  servlet:
    context-path: /api
spring:
  application:
    name: zn1-backend
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://jizy.top:3306/zn1?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: jizy1510
  mybatis-plus:
    configuration:
      #是否启用数据库驼峰命名
      map-underscore-to-camel-case: false
      # 仅在开发环境开启日志
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
      db-config:
        logic-delete-field: isDelete # 全局逻辑删除的实体字段名
        logic-delete-value: 1 # 逻辑已删除值（默认为 1）
        logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.jizy.zn1backend.controller
  #  上传文件限制
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
#  MinIO配置
minio:
  endpoint: http://jizy.top:9000   # MinIO服务器地址
  access-key: cNkjvBhzDMg9PQpWtv4e       # 登录用户名
  secret-key: gPRQaI4Wc2eFh0lMBL9c07Ev9Bli1zPYiA4bAhEv       # 登录密码
  bucket-name: zn1          # 存储桶名称（需提前在MinIO控制台创建）
  secure: false                     # 是否HTTPS（本地测试false）
